// Find by Beacon - Rich Mock Database

export const categories = [
  { id: "home-services", name: "Home Services", icon: "🏠", slug: "home-services" },
  { id: "beauty-care", name: "Beauty & Personal Care", icon: "💅", slug: "beauty-care" },
  { id: "food-hospitality", name: "Food & Hospitality", icon: "🍽️", slug: "food-hospitality" },
  { id: "professional-services", name: "Professional Services", icon: "💼", slug: "professional-services" },
  { id: "care-community", name: "Care & Family Services", icon: "❤️", slug: "care-community" },
  { id: "retail-products", name: "Retail & Local Products", icon: "🛍️", slug: "retail-products" }
];

export const subcategories = [
  { id: "plumbers", categoryId: "home-services", name: "Plumbers" },
  { id: "electricians", categoryId: "home-services", name: "Electricians" },
  { id: "cleaners", categoryId: "home-services", name: "Cleaners" },
  { id: "lawn-care", categoryId: "home-services", name: "Lawn Care" },
  { id: "contractors", categoryId: "home-services", name: "Contractors" },
  { id: "hairdressers", categoryId: "beauty-care", name: "Hairdressers" },
  { id: "barbers", categoryId: "beauty-care", name: "Barbers" },
  { id: "nail-techs", categoryId: "beauty-care", name: "Nail Technicians" },
  { id: "restaurants", categoryId: "food-hospitality", name: "Restaurants" },
  { id: "guesthouses", categoryId: "food-hospitality", name: "Guesthouses" },
  { id: "caterers", categoryId: "food-hospitality", name: "Caterers" },
  { id: "consultants", categoryId: "professional-services", name: "Consultants" },
  { id: "coaches", categoryId: "professional-services", name: "Coaches" },
  { id: "tutors", categoryId: "care-community", name: "Tutors" },
  { id: "funeral-agencies", categoryId: "care-community", name: "Funeral Agencies" },
  { id: "skincare-brands", categoryId: "retail-products", name: "Skincare & Natural Products" }
];

export const locations = [
  { id: "chaguanas", name: "Chaguanas", region: "Central Trinidad", country: "Trinidad and Tobago" },
  { id: "san-fernando", name: "San Fernando", region: "South Trinidad", country: "Trinidad and Tobago" },
  { id: "port-of-spain", name: "Port of Spain", region: "North Trinidad", country: "Trinidad and Tobago" },
  { id: "arima", name: "Arima", region: "East Trinidad", country: "Trinidad and Tobago" },
  { id: "scarborough", name: "Scarborough", region: "Tobago", country: "Trinidad and Tobago" },
  { id: "couva", name: "Couva", region: "Central Trinidad", country: "Trinidad and Tobago" }
];

export const businesses = [
  // PAID MEMBERS
  {
    id: "biz-1",
    business_name: "Caribbean Flow Plumbing & Renovations",
    slug: "caribbean-flow-plumbing",
    description: "Caribbean Flow Plumbing offers premier plumbing, leak detection, water pump installation, and complete bathroom renovation services. Serving both residential and commercial clients across Central Trinidad with reliable, transparent support.",
    short_description: "Professional plumbing & renovation specialists in Chaguanas.",
    category_id: "home-services",
    subcategory_id: "plumbers",
    location_id: "chaguanas",
    country: "Trinidad and Tobago",
    city: "Chaguanas",
    community: "Lendore Village",
    phone: "+1 (868) 555-FLOW",
    email: "info@caribflowplumbing.com",
    whatsapp: "https://wa.me/18685553569",
    website: "https://www.caribflowplumbing.com",
    facebook: "https://facebook.com/caribbeanflow",
    instagram: "https://instagram.com/caribflow_plumbing",
    tiktok: "",
    logo: "🚰",
    claimed_status: "claimed",
    membership_status: "member", // Beacon Member
    profile_type: "paid",
    verification_status: "verified",
    trust_score: 96,
    home_access_certified: true,
    review_average: 4.9,
    review_count: 24,
    has_booking: true,
    has_quote_request: true,
    has_offers: true,
    is_featured: true,
    is_sponsored: false,
    gallery_images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=500&auto=format&fit=crop&q=60"
    ],
    services: ["Residential Leak Repair", "Water Tank & Pump Installation", "Bathroom Re-tiling", "Commercial Drain Cleaning", "Emergency Support"],
    updates: "We are currently running a special coupon discount for Chaguanas residents this month. Quote 'BEACONFLOW' when requesting a visit!",
    faqs: [
      { q: "Do you charge a call-out fee?", a: "We provide free estimates for jobs within Chaguanas. Other areas carry a small call-out fee which is deducted from your final invoice if you proceed." },
      { q: "Are you licensed?", a: "Yes, all our senior plumbers are fully licensed and hold Home Access Certification." }
    ]
  },
  {
    id: "biz-2",
    business_name: "Mahogany & Lace Bridal Beauty",
    slug: "mahogany-lace-beauty",
    description: "Mahogany & Lace is an exclusive beauty studio specializing in luxury bridal hair design, high-definition makeup, and premium nail aesthetics. Led by award-winning stylist Aurelia Belmont.",
    short_description: "Luxury bridal beauty & styling studio in San Fernando.",
    category_id: "beauty-care",
    subcategory_id: "hairdressers",
    location_id: "san-fernando",
    country: "Trinidad and Tobago",
    city: "San Fernando",
    community: "Bel Air",
    phone: "+1 (868) 555-GLAM",
    email: "aurelia@mahoganylace.com",
    whatsapp: "https://wa.me/18685554526",
    website: "https://www.mahoganylace.com",
    facebook: "",
    instagram: "https://instagram.com/mahoganylace_bridal",
    tiktok: "",
    logo: "💇‍♀️",
    claimed_status: "claimed",
    membership_status: "member",
    profile_type: "paid",
    verification_status: "verified",
    trust_score: 98,
    home_access_certified: false,
    review_average: 5.0,
    review_count: 32,
    has_booking: true,
    has_quote_request: false,
    has_offers: true,
    is_featured: true,
    is_sponsored: false,
    gallery_images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=500&auto=format&fit=crop&q=60"
    ],
    services: ["Bridal Makeup Consultations", "Luxury Hair Extensions", "Gel Overlay Nail Art", "Airbrush Makeup Packages"],
    updates: "Now booking for the upcoming wedding season. Schedule a consultation via our booking portal to lock in your date.",
    faqs: [
      { q: "Do you travel to venues?", a: "Yes, our bridal package includes on-site styling anywhere across Trinidad and Tobago." }
    ]
  },
  {
    id: "biz-3",
    business_name: "Island Breeze Guest Villa",
    slug: "island-breeze-villa",
    description: "Nestled in the lush hills overlooking the Caribbean Sea, Island Breeze offers premium boutique accommodation, private pool facilities, and customized local tours.",
    short_description: "Stunning boutique guesthouse & villas in Tobago.",
    category_id: "food-hospitality",
    subcategory_id: "guesthouses",
    location_id: "scarborough",
    country: "Trinidad and Tobago",
    city: "Scarborough",
    community: "Bacolet Heights",
    phone: "+1 (868) 555-REST",
    email: "booking@islandbreeze.com",
    whatsapp: "https://wa.me/18685557378",
    website: "https://www.islandbreeze.com",
    facebook: "",
    instagram: "https://instagram.com/islandbreeze_tobago",
    tiktok: "",
    logo: "🏝️",
    claimed_status: "claimed",
    membership_status: "member",
    profile_type: "paid",
    verification_status: "verified",
    trust_score: 95,
    home_access_certified: false,
    review_average: 4.8,
    review_count: 18,
    has_booking: true,
    has_quote_request: true,
    has_offers: true,
    is_featured: false,
    is_sponsored: true, // Sponsored Result
    gallery_images: [
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=500&auto=format&fit=crop&q=60"
    ],
    services: ["Luxury Master Suites", "Full Guesthouse Rental", "Tobago Reef Excursions", "Airport Shuttle Service"],
    updates: "Tobago resident discounts available for weekend getaways. Use the View Offers tab below to check availability.",
    faqs: [
      { q: "Is breakfast included?", a: "Yes, complimentary local breakfast is served daily between 7:30 AM and 10:00 AM." }
    ]
  },
  {
    id: "biz-4",
    business_name: "Belgrave & Sons Dignified Funeral Services",
    slug: "belgrave-funeral-services",
    description: "Belgrave & Sons has served the North Trinidad community with compassionate, highly structured, and dignified funeral arrangements for over three decades.",
    short_description: "Providing trusted, sensitive funeral arrangements in Port of Spain.",
    category_id: "care-community",
    subcategory_id: "funeral-agencies",
    location_id: "port-of-spain",
    country: "Trinidad and Tobago",
    city: "Port of Spain",
    community: "Woodbrook",
    phone: "+1 (868) 555-CARE",
    email: "support@belgravefuneral.com",
    whatsapp: "https://wa.me/18685552273",
    website: "https://www.belgravefuneral.com",
    facebook: "",
    instagram: "",
    tiktok: "",
    logo: "🕯️",
    claimed_status: "claimed",
    membership_status: "member",
    profile_type: "paid",
    verification_status: "verified",
    trust_score: 99,
    home_access_certified: false,
    review_average: 4.9,
    review_count: 40,
    has_booking: true,
    has_quote_request: true,
    has_offers: false,
    is_featured: true,
    is_sponsored: false,
    gallery_images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=60"
    ],
    services: ["Full Funeral Coordination", "Memorial & Repast Catering", "Repatriation Services", "Pre-planning Consultations"],
    updates: "We have extended our consultation suite to support online video planning sessions for families living abroad.",
    faqs: [
      { q: "Do you offer pre-payment plans?", a: "Yes, our pre-planning options allow you to choose and secure details in advance to protect your family." }
    ]
  },
  {
    id: "biz-5",
    business_name: "Apex Academic Tutors",
    slug: "apex-academic-tutors",
    description: "Apex Tutors delivers elite online and in-person tutoring programs in CSEC Mathematics, Add Math, Physics, and Chemistry. Our students average a 92% pass rate with grade 1 profiles.",
    short_description: "Premium CSEC Math & Science tuition in East Trinidad.",
    category_id: "care-community",
    subcategory_id: "tutors",
    location_id: "arima",
    country: "Trinidad and Tobago",
    city: "Arima",
    community: "Santa Rosa",
    phone: "+1 (868) 555-MATH",
    email: "tutors@apextt.com",
    whatsapp: "https://wa.me/18685556284",
    website: "https://www.apextt.com",
    facebook: "",
    instagram: "https://instagram.com/apextutors_tt",
    tiktok: "",
    logo: "✏️",
    claimed_status: "claimed",
    membership_status: "member",
    profile_type: "paid",
    verification_status: "verified",
    trust_score: 97,
    home_access_certified: true,
    review_average: 4.9,
    review_count: 15,
    has_booking: true,
    has_quote_request: false,
    has_offers: true,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [
      "https://images.unsplash.com/photo-1577896851231-70ee18881754?w=500&auto=format&fit=crop&q=60"
    ],
    services: ["CSEC Mathematics Group Classes", "One-on-One Chemistry Tutors", "SBA Review & Guidance sessions"],
    updates: "Registration is now open for our intensive July-August headstart classes.",
    faqs: [
      { q: "Do you tutor in-person?", a: "Yes, we run hybrid classes with physically-spaced sessions at our Arima center and interactive Zoom modules." }
    ]
  },

  // FREE LISTINGS
  {
    id: "biz-6",
    business_name: "Green Coast Cleaners",
    slug: "green-coast-cleaners",
    description: "Green Coast Cleaners offers standard residential home cleaning, carpet sanitation, and post-construction cleanup services across Central Trinidad.",
    short_description: "Home & office cleaning services in Couva.",
    category_id: "home-services",
    subcategory_id: "cleaners",
    location_id: "couva",
    country: "Trinidad and Tobago",
    city: "Couva",
    community: "Roystonia",
    phone: "+1 (868) 555-8829",
    email: "greencoastclean@gmail.com",
    whatsapp: "https://wa.me/18685558829",
    website: "https://greencoastclean.wordpress.com",
    facebook: "https://facebook.com/greencoast",
    instagram: "",
    tiktok: "",
    logo: "🧹",
    claimed_status: "unclaimed",
    membership_status: "free", // Free tier
    profile_type: "free",
    verification_status: "unverified",
    trust_score: null,
    home_access_certified: false,
    review_average: 4.2,
    review_count: 3,
    has_booking: false,
    has_quote_request: false,
    has_offers: false,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [],
    services: ["Residential Home Cleaning", "Office Janitorial Support"]
  },
  {
    id: "biz-7",
    business_name: "Chaguanas Local Food Box",
    slug: "chaguanas-food-box",
    description: "Authentic local meals, rotis, and curries made fresh daily. Order ahead for pickup or central delivery.",
    short_description: "Tasty local lunches and rotis in Chaguanas.",
    category_id: "food-hospitality",
    subcategory_id: "restaurants",
    location_id: "chaguanas",
    country: "Trinidad and Tobago",
    city: "Chaguanas",
    community: "Montrose",
    phone: "+1 (868) 555-3287",
    email: "",
    whatsapp: "https://wa.me/18685553287",
    website: "",
    facebook: "",
    instagram: "",
    tiktok: "",
    logo: "🍛",
    claimed_status: "unclaimed",
    membership_status: "free",
    profile_type: "free",
    verification_status: "unverified",
    trust_score: null,
    home_access_certified: false,
    review_average: 4.5,
    review_count: 5,
    has_booking: false,
    has_quote_request: false,
    has_offers: false,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [],
    services: ["Local Lunch Boxes", "Catering Platters"]
  },
  {
    id: "biz-8",
    business_name: "Raw & Sun Coconut Organics",
    slug: "raw-sun-organics",
    description: "Handcrafted pure cold-pressed coconut oil, raw cocoa butter soaps, and natural Caribbean body scrubs made in small batches in Tobago.",
    short_description: "Organic coconut oil and natural skincare remedies.",
    category_id: "retail-products",
    subcategory_id: "skincare-brands",
    location_id: "scarborough",
    country: "Trinidad and Tobago",
    city: "Scarborough",
    community: "Signal Hill",
    phone: "+1 (868) 555-COCO",
    email: "rawcoco@gmail.com",
    whatsapp: "https://wa.me/18685552626",
    website: "",
    facebook: "",
    instagram: "https://instagram.com/rawsun_skincare",
    tiktok: "",
    logo: "🥥",
    claimed_status: "claimed",
    membership_status: "free",
    profile_type: "free",
    verification_status: "unverified",
    trust_score: null,
    home_access_certified: false,
    review_average: 4.6,
    review_count: 6,
    has_booking: false,
    has_quote_request: false,
    has_offers: false,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [],
    services: ["Virgin Coconut Oil Bottles", "Organic Skincare Soap Bars"]
  },
  {
    id: "biz-9",
    business_name: "Renegade Barbells Gym",
    slug: "renegade-barbells",
    description: "Standard local gym facility with free weights, group workouts, and fitness trainers in Chaguanas.",
    short_description: "Weights and core training studio in Chaguanas.",
    category_id: "beauty-care",
    subcategory_id: "barbers",
    location_id: "chaguanas",
    country: "Trinidad and Tobago",
    city: "Chaguanas",
    community: "Montrose",
    phone: "+1 (868) 555-GYMM",
    email: "",
    whatsapp: "https://wa.me/18685554966",
    website: "",
    facebook: "",
    instagram: "",
    tiktok: "",
    logo: "🏋️",
    claimed_status: "unclaimed",
    membership_status: "free",
    profile_type: "free",
    verification_status: "unverified",
    trust_score: null,
    home_access_certified: false,
    review_average: 4.0,
    review_count: 2,
    has_booking: false,
    has_quote_request: false,
    has_offers: false,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [],
    services: ["Daily Gym Entry Pass", "Personal Coaching Sessions"]
  },
  {
    id: "biz-10",
    business_name: "San Fernando Electrical Services",
    slug: "sando-electrical",
    description: "Electrical installation, wiring, breaker box troubleshooting, and light repairs for residential homes.",
    short_description: "Residential electrical technician.",
    category_id: "home-services",
    subcategory_id: "electricians",
    location_id: "san-fernando",
    country: "Trinidad and Tobago",
    city: "San Fernando",
    community: "Marabella",
    phone: "+1 (868) 555-9182",
    email: "sandoelect@hotmail.com",
    whatsapp: "https://wa.me/18685559182",
    website: "",
    facebook: "",
    instagram: "",
    tiktok: "",
    logo: "⚡",
    claimed_status: "unclaimed",
    membership_status: "free",
    profile_type: "free",
    verification_status: "unverified",
    trust_score: null,
    home_access_certified: false,
    review_average: 4.1,
    review_count: 4,
    has_booking: false,
    has_quote_request: false,
    has_offers: false,
    is_featured: false,
    is_sponsored: false,
    gallery_images: [],
    services: ["House Circuit Wiring", "Fault Inspections"]
  }
];

export const professionals = [
  {
    id: "prof-1",
    business_id: "biz-2",
    name: "Aurelia Belmont",
    slug: "aurelia-belmont",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=60",
    role: "Founder & Lead Bridal Stylist",
    bio: "Aurelia has over 10 years of experience shaping premium styles for bridal campaigns across the southern Caribbean. She trained in Paris and is passionate about highlighting natural hair textures.",
    experience: "12 Years",
    specialties: ["Luxury Updos", "Airbrush Makeup Art", "Gel Sculpting"],
    credentials: "Diploma in Advanced Cosmetics (Paris Academy of Beauty)",
    location: "San Fernando, Trinidad",
    booking_link_optional: "https://book.mahoganylace.com",
    is_visible: true
  },
  {
    id: "prof-2",
    business_id: "biz-1",
    name: "Marcus Gopaul",
    slug: "marcus-gopaul",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=60",
    role: "Chief Leak Specialist",
    bio: "Marcus is a third-generation plumber who specializes in non-invasive thermal leak detection and water system design. He holds multiple safety and trade certifications.",
    experience: "15 Years",
    specialties: ["Thermal Imaging Leak Search", "Pressure Grid Design", "Safety Inspections"],
    credentials: "Level 3 Trade Certification (UTT)",
    location: "Chaguanas, Trinidad",
    booking_link_optional: "https://book.caribflowplumbing.com/marcus",
    is_visible: true
  }
];

export const reviews = [
  { id: "rev-1", business_id: "biz-1", reviewer_name: "Devesh Rambaran", rating: 5, review_text: "Marcus arrived on time, found a pipe leak inside my living room wall using thermal equipment in 15 minutes, and patched it without tearing up the tiles. Highly recommended!", status: "approved", created_at: "2026-05-12" },
  { id: "rev-2", business_id: "biz-1", reviewer_name: "Sarah Andrews", rating: 5, review_text: "Top notch professional work. They cleaned up everything before leaving.", status: "approved", created_at: "2026-06-02" },
  { id: "rev-3", business_id: "biz-2", reviewer_name: "Nalini Mohammed", rating: 5, review_text: "Aurelia made me feel like royalty on my wedding day! The hair and airbrush makeup stayed flawless even in the Tobago humidity.", status: "approved", created_at: "2026-04-18" },
  { id: "rev-4", business_id: "biz-6", reviewer_name: "John Smith", rating: 4, review_text: "Good standard cleaning, they were thorough with the kitchen cabinet surfaces.", status: "approved", created_at: "2026-03-24" }
];

export const offers = [
  {
    id: "off-1",
    business_id: "biz-1",
    title: "Chaguanas Resident Plumbing Checkup Special",
    description: "Get 15% off standard water pressure testing and pipe inspections. Exclusively for Central residents this month.",
    image: "https://images.unsplash.com/photo-1581094288338-2314dddb7eed?w=400&auto=format&fit=crop&q=60",
    start_date: "2026-06-01",
    end_date: "2026-06-30",
    terms: "Applies to Chaguanas addresses only. Cannot combine with other promotions.",
    cta_label: "Claim Coupon Code",
    cta_url: "#",
    status: "active"
  },
  {
    id: "off-2",
    business_id: "biz-2",
    title: "Luxury Nail Set & Gel Overlay Promo",
    description: "Receive a free conditioning hand treatment when you book any Gel Overlay extension set.",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&auto=format&fit=crop&q=60",
    start_date: "2026-06-15",
    end_date: "2026-07-15",
    terms: "Pre-booking required. In-studio only.",
    cta_label: "Book Appointment",
    cta_url: "#",
    status: "active"
  },
  {
    id: "off-3",
    business_id: "biz-3",
    title: "Tobago Resident Staycation Special",
    description: "Rent the entire boutique villa for three nights and pay for only two. Island resident ID required at check-in.",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&auto=format&fit=crop&q=60",
    start_date: "2026-06-01",
    end_date: "2026-08-31",
    terms: "Subject to villa availability. Trini/Tobago residents only.",
    cta_label: "Request Staycation Dates",
    cta_url: "#",
    status: "active"
  }
];

export const spotlights = [
  {
    id: "spot-1",
    business_id: "biz-2",
    title: "Bridging French Technique with Caribbean Textures",
    story: "Aurelia Belmont returned to San Fernando after styling in Paris. Discover how she founded Mahogany & Lace and why bridal parties travel across Trinidad just to get styled in her chair.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=60",
    category: "Beauty & Style",
    published_at: "2026-06-10",
    status: "published"
  },
  {
    id: "spot-2",
    business_id: "biz-1",
    title: "Running a Third-Generation Service Business with Pride",
    story: "Leak detection isn't just about pipes; it's about safeguarding Caribbean homes. Marcus Gopaul talks about digital tools and why honesty remains the main tool in his box.",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=60",
    category: "Home Services",
    published_at: "2026-06-05",
    status: "published"
  }
];

export const events = [
  {
    id: "eve-1",
    title: "How to Build Consistent Customer Reviews Online",
    speaker: "Carla Parris (Beacon Business Success Team)",
    description: "Learn how to ask, coordinate, verify, and promote customer reviews on WhatsApp and directories to build visible business value.",
    date: "2026-07-15",
    time: "6:00 PM AST",
    registration_url: "https://webinar.caribbeacon.com/reviews",
    is_member_only: false,
    status: "active"
  },
  {
    id: "eve-2",
    title: "Direct Pricing Strategy for Caribbean Contractors",
    speaker: "David Belgrave (Finance Lead)",
    description: "A step-by-step masterclass on tracking materials, scheduling labor rates, and building professional proposals that secure bigger projects.",
    date: "2026-07-28",
    time: "7:00 PM AST",
    registration_url: "https://webinar.caribbeacon.com/pricing",
    is_member_only: true,
    status: "active"
  }
];

export const ads = [
  {
    id: "ad-1",
    business_id: "biz-1",
    title: "Leaking Pipe? Get Verified Plumbing Support Today",
    placement_type: "homepage-banner",
    image: "https://images.unsplash.com/photo-1581094288338-2314dddb7eed?w=800&auto=format&fit=crop&q=60",
    target_url: "#profile/biz-1",
    sponsored_label: "Featured Member",
    status: "active"
  },
  {
    id: "ad-2",
    business_id: "biz-3",
    title: "Book Tobago's Best Boutique Guest Villa",
    placement_type: "category-sponsor",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&auto=format&fit=crop&q=60",
    target_url: "#profile/biz-3",
    sponsored_label: "Sponsored Listing",
    status: "active"
  }
];
